### ISSUE TITLE
lora finetuning link

### ISSUE THREAD

**Issue by YotamWolf** [BatouResearch/Cog-SDXL-ControlNet-LoRA#2]
Can you add the link to the lora finetuning training you guys used on replicate? so the community can add more styles?

**Comment by Pau-Lozano** [comment]
Hi @YotamWolf, I'll be happy to help, but I'm not entirely sure to understand your request.
Do you mean the weight urls used on the model's examples page? ([this?](https://replicate.com/batouresearch/sdxl-controlnet-lora/examples))
